'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Copy, Check, X, ChevronDown, ChevronUp, Sparkles } from 'lucide-react';

interface FixSuggestion {
  id: string;
  suggestion: string;
  fixedCode?: string | null;
  confidence: number;
  status: string;
  createdAt: string;
}

interface FixSuggestionCardProps {
  suggestion: FixSuggestion;
  onDismiss: (id: string) => void;
  onApply: (id: string) => void;
}

export function FixSuggestionCard({ suggestion, onDismiss, onApply }: FixSuggestionCardProps) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const handleCopy = async () => {
    if (suggestion.fixedCode) {
      await navigator.clipboard.writeText(suggestion.fixedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const confidenceColor = (confidence: number) => {
    if (confidence >= 0.9) return 'text-green-600 bg-green-50 border-green-200';
    if (confidence >= 0.7) return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    return 'text-orange-600 bg-orange-50 border-orange-200';
  };

  const confidenceLabel = (confidence: number) => {
    if (confidence >= 0.9) return 'High';
    if (confidence >= 0.7) return 'Medium';
    return 'Low';
  };

  if (suggestion.status === 'dismissed') {
    return null;
  }

  return (
    <Card className="border-l-4 border-l-purple-500">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div className="flex items-start gap-3 flex-1">
            <div className="mt-1">
              <Sparkles className="h-5 w-5 text-purple-500" />
            </div>
            <div className="flex-1">
              <CardTitle className="text-base font-semibold flex items-center gap-2">
                AI-Generated Fix Suggestion
                <Badge variant="outline" className={`${confidenceColor(suggestion.confidence)}`}>
                  {confidenceLabel(suggestion.confidence)} Confidence ({Math.round(suggestion.confidence * 100)}%)
                </Badge>
              </CardTitle>
              <CardDescription className="mt-1 text-sm">
                Generated by AI • {new Date(suggestion.createdAt).toLocaleDateString()}
              </CardDescription>
            </div>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        <div>
          <p className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
            {suggestion.suggestion}
          </p>
        </div>

        {suggestion.fixedCode && (
          <div>
            <button
              onClick={() => setExpanded(!expanded)}
              className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2 hover:text-purple-600"
            >
              {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
              {expanded ? 'Hide' : 'Show'} suggested code
            </button>

            {expanded && (
              <div className="relative">
                <pre className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto text-sm">
                  <code>{suggestion.fixedCode}</code>
                </pre>
                <Button
                  size="sm"
                  variant="ghost"
                  className="absolute top-2 right-2 h-8 px-2"
                  onClick={handleCopy}
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-green-500" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </Button>
              </div>
            )}
          </div>
        )}

        <div className="flex gap-2 pt-2">
          {suggestion.status === 'pending' && (
            <>
              <Button
                size="sm"
                variant="default"
                onClick={() => onApply(suggestion.id)}
                className="bg-purple-600 hover:bg-purple-700"
              >
                <Check className="h-4 w-4 mr-1" />
                Mark as Applied
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => onDismiss(suggestion.id)}
              >
                <X className="h-4 w-4 mr-1" />
                Dismiss
              </Button>
            </>
          )}
          {suggestion.status === 'applied' && (
            <Badge variant="outline" className="text-green-600 bg-green-50 border-green-200">
              <Check className="h-3 w-3 mr-1" />
              Applied
            </Badge>
          )}
        </div>

        <div className="pt-2 border-t border-gray-200 dark:border-gray-700">
          <p className="text-xs text-gray-500 dark:text-gray-400">
            ⚠️ AI-generated suggestions should be reviewed before applying. Always test changes before deploying.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
